### ISSUE TITLE
[REQ] add a (GH-compliant) license file

### ISSUE THREAD

**Issue by MarcoRavich** [omerkolcak/GANs-Drum-Pattern-Generator#1]
Hi there, 1st of all thanks for your awesome work !

Since we've "doxed" it in our [HyMPS project](https://github.com/forart/HyMPS#readme) (under the [AUDIO](https://github.com/forart/HyMPS#-) \ [AI-based projects page](https://github.com/forart/HyMPS/blob/main/AIaudio.md#--) \ [Drums subsection](https://github.com/forart/HyMPS/blob/main/AIaudio.md#drums-)), can you please add a "GH-compliant" license file ?

Expliciting licensing terms is extremely important to let other devs (and not only) understand how to reuse/adapt/modify your code in other open projects and vice-versa.

Although it may sounds like a minor aspect, license file omission obviously causes an inconsistent generation of the relative badge too:

![](https://flat.badgen.net/github/license/omerkolcak/GANs-Drum-Pattern-Generator/?label=LICENSE)
(badge-generator URL: https://flat.badgen.net/github/license/omerkolcak/GANs-Drum-Pattern-Generator/?label=LICENSE)

Anyway you can easily choose a "correct" one through the GH's license wizard tool.

Last but not least, let us know how we could improve - in your opinion - categorization/sorting of collected projects in order to push their evolution by favouring collaborations between developers (and not only).

Thanks in advance.

**Comment by omerkolcak** [comment]
Hello, 

First of all thank you for noticing my work. I have added a license file as you wish. It is very nice to see all this interesting works done by other developers, i am execited to look at them and maybe collabrate with them. In my opinion, categorization of the repositories are seemed very clear to me and i can easily find different repositories by their respective fields of interest. 

Thank you again.
